"""Статусы заказа и допустимые переходы (MVP)."""

STATUS_NEW = "новый"
STATUS_PROCESSING = "в_обработке"
STATUS_ASSEMBLED = "собран"
STATUS_ISSUED = "выдан"
STATUS_CANCELLED = "отменен"

ORDER_STATUSES = (
    STATUS_NEW,
    STATUS_PROCESSING,
    STATUS_ASSEMBLED,
    STATUS_ISSUED,
    STATUS_CANCELLED,
)

STATUS_LABELS = {
    STATUS_NEW: "Новый",
    STATUS_PROCESSING: "В обработке",
    STATUS_ASSEMBLED: "Собран",
    STATUS_ISSUED: "Выдан",
    STATUS_CANCELLED: "Отменён",
}

ALLOWED_TRANSITIONS: dict[str, set[str]] = {
    STATUS_NEW: {STATUS_PROCESSING, STATUS_CANCELLED},
    STATUS_PROCESSING: {STATUS_ASSEMBLED, STATUS_CANCELLED},
    STATUS_ASSEMBLED: {STATUS_ISSUED, STATUS_CANCELLED},
    STATUS_ISSUED: set(),
    STATUS_CANCELLED: set(),
}

CLIENT_CANCELLABLE_STATUSES = {
    STATUS_NEW,
    STATUS_PROCESSING,
    STATUS_ASSEMBLED,
}

DELIVERY_PICKUP = "самовывоз"
DELIVERY_COURIER = "доставка"
